### PR TITLE
Updates for finishing classification tasks without getting stuck in SGD

### PR DESCRIPTION
**Pull request by kkarrancsu**
updates to get SVC, MLP, and GP to not get stuck w/ skewed data by limiting total number of allowed iterations before solver terminates.

Added adaboost configuration json file.

### CODE REVIEW

**Comment by kkarrancsu** [comment]
I apologize, but I didn't put the `max_iter` variable in the `root_variables` key in the JSON files which were modified.  I can do another pull request, but think it might be easier if you made the changes directly?  I can do either, let me know what you prefer.

**Comment by bcyphers** [comment]
No problem, I can make the change on master.

Also, it looks like the GaussianProcessClassifier defaults to `max_iter_predict=100`. Is there a reason we should raise it to 5000?

**Comment by bcyphers** [comment]
I'm going to commit the SVM fix, and roll back the gp and mlp changes for now.

**Comment by kkarrancsu** [comment]
Ok, great, good point about the GP and MLP, better to leave it out.  Users can provide their own json configuration files if they wish to alter the default behavior.

**Pull request merged**
