### PR TITLE
First REST API idea.

### PR DESCRIPTION
**Pull request by jobliz**
A pull request to expose currently available functionality through a REST API implemented with Flask. Details on issue #82.

### CODE REVIEW

**Comment by jobliz** [comment]
Going through the code thinking about how to test the API I remembered the choices and tradeoffs I made when doing the `rest_api_server.py` script. Seeing that, for example, the `add_arguments_sql` function takes an argparse instance (as well as the other `add_arguments_*` functions) and that these functions are a fundamental part of ATM, I choose to tie the Flask app creation to an argument parser too, so that every available command line switch could also configure the REST API on the go. There's also several globals going around on the script, below the `if __name__ == '__main__'` conditional.

All this is way too coupled, which makes testing harder. Each test under this design would have to replicate an argparser instance before it can be run. I think this __can__ be done in a base class, but I'll mull it over a bit more to see if a better idea comes to mind.

**Comment by RogerTangos** [comment]
Hey @jobliz. Thank you for the PR. I'm newly on this project, but also have an API on my roadmap, so think your contribution is really useful. I'd like to make some additional commits on the branch. Are you interested in continuing to work on this?

Here are some thoughts. They're numbered and lettered for discussion

1. There's another (private) repo which has started building an API for ATM. It has a better idea of usecases, but I think that the design and implementation here are generally better thought out.
2. I like that the endpoints follow the schema
3. There are a few endpoints that will still be required for someone to build a UI:
  a. an endpoint to download a dataset
  b. summarization endpoints (These are very subjective, but seem to be quite useful to the viz group's efforts):
    - an endpoint showing scores of the hyperpartitions in each step of a datarun
    - an endpoint summarizing notable classifiers in a datarun
5. I agree that the coupling is too tight here. A non-`database.py` file with direct access to the database rubs me the wrong way.
  a. `to_json` methods to serialize instances of the `database` objects could be a strategy here. I think that would allow for easier testing too.
  b. I'm interested in hearing about other options as well
6. It would be awfully nice if the API were browsable.
  a. On another project, I did this with the Django REST framework, but haven't used anything like that in Flask.
  b. A quick google search yields [Flask-API](https://www.flaskapi.org/) and [Flask-RESTful](https://flask-restful.readthedocs.io/en/latest/).
7.  I'm also open to non-REST solutions. A coworker suggested looking at GraphQL, which I don't have any experience with. 
8. I don't think this is ready to do into master, but would like to create a new branch from it and start working there.

**Comment by RogerTangos** [comment]
@jobliz - ping on this. Is this something you'd be interested in continuing to work on?

**Comment by RogerTangos** [comment]
I'm closing this PR in favor of continued development on the rest-api branch.

**Pull request closed without merging**
